version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${APP_DB_USER:-image_app}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME:-image_generation}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_wal:/var/lib/postgresql/data/pg_wal
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}" -h localhost',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        failure_action: rollback
        monitor: 30s
        order: start-first

  app:
    image: ${APP_IMAGE:-image-generation-app:latest}
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      DATABASE_URL: postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres:5432/${APP_DB_NAME}
      AUTH_SECRET: ${AUTH_SECRET}
      NODE_ENV: ${NODE_ENV:-production}
      VOLCENGINE_ACCESS_KEY: ${VOLCENGINE_ACCESS_KEY}
      VOLCENGINE_SECRET_KEY: ${VOLCENGINE_SECRET_KEY}
      VOLCENGINE_REGION: ${VOLCENGINE_REGION}
      VOLCENGINE_ENDPOINT: ${VOLCENGINE_ENDPOINT}
      VOLCENGINE_BUCKET_NAME: ${VOLCENGINE_BUCKET_NAME}
      ARK_API_KEY: ${ARK_API_KEY}
      ARK_BASE_URL: ${ARK_BASE_URL}
      ARK_MODEL: ${ARK_MODEL}
      SEEDREAM_API_KEY: ${SEEDREAM_API_KEY}
      SEEDREAM_BASE_URL: ${SEEDREAM_BASE_URL}
      SEEDREAM_MODEL: ${SEEDREAM_MODEL}
      SEEDREAM_CONCURRENCY: ${SEEDREAM_CONCURRENCY:-20}
      QUEUE_CONCURRENCY: ${QUEUE_CONCURRENCY:-5}
      CRON_TASK_ENQUEUE_ENABLED: ${CRON_TASK_ENQUEUE_ENABLED:-true}
      CRON_TASK_ENQUEUE_INTERVAL: ${CRON_TASK_ENQUEUE_INTERVAL}
      CRON_TASK_ENQUEUE_BATCH_SIZE: ${CRON_TASK_ENQUEUE_BATCH_SIZE:-20}
      CRON_TASK_TIMEOUT_ENABLED: ${CRON_TASK_TIMEOUT_ENABLED:-true}
      CRON_TASK_TIMEOUT_INTERVAL: ${CRON_TASK_TIMEOUT_INTERVAL}
      CRON_TASK_TIMEOUT_MINUTES: ${CRON_TASK_TIMEOUT_MINUTES:-10}
      CRON_ORDER_CLOSE_ENABLED: ${CRON_ORDER_CLOSE_ENABLED:-true}
      CRON_ORDER_CLOSE_INTERVAL: ${CRON_ORDER_CLOSE_INTERVAL}
      CRON_ORDER_CLOSE_BATCH_SIZE: ${CRON_ORDER_CLOSE_BATCH_SIZE:-50}
      GIFT_AMOUNT: ${GIFT_AMOUNT:-0}
      ANALYSIS_PRICE: ${ANALYSIS_PRICE:-0}
      WECHAT_PAY_APPID: ${WECHAT_PAY_APPID}
      WECHAT_PAY_MCHID: ${WECHAT_PAY_MCHID}
      WECHAT_PAY_API_V3_KEY: ${WECHAT_PAY_API_V3_KEY}
      WECHAT_PAY_SERIAL_NO: ${WECHAT_PAY_SERIAL_NO}
      WECHAT_PAY_PRIVATE_KEY: ${WECHAT_PAY_PRIVATE_KEY}
      WECHAT_PAY_NOTIFY_URL: ${WECHAT_PAY_NOTIFY_URL}
      WECHAT_PAY_PLATFORM_CERT: ${WECHAT_PAY_PLATFORM_CERT}
      WECHAT_PAY_PLATFORM_CERT_SERIAL_NO: ${WECHAT_PAY_PLATFORM_CERT_SERIAL_NO}
      ALIPAY_APPID: ${ALIPAY_APPID}
      ALIPAY_PRIVATE_KEY: ${ALIPAY_PRIVATE_KEY}
      ALIPAY_PUBLIC_KEY: ${ALIPAY_PUBLIC_KEY}
      ALIPAY_NOTIFY_URL: ${ALIPAY_NOTIFY_URL}
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker

volumes:
  postgres_data:
    driver: local
  postgres_wal:
    driver: local
